### ISSUE TITLE
Relation to "Nebula 3 Device" by radeonlabs?

### ISSUE THREAD

**Issue by 4censord** [gscept/nebula#165]
Is this project in any way related to the Nebula engine from [radeonlabs](https://en.wikipedia.org/wiki/Radon_Labs)?

**Comment by kaffeewolf** [comment]
After Radonlabs shut down we continued development of the then last public snapshot of nebula 3 from radonlabs, called [https://github.com/gscept/nebula-trifid](url) for use in university education. It has different rendering backends using dx10, gl4 and vulkan and tooling written in QT4 and was used to create smaller game projects in university.

This project is kind of a refresh, that is still in the spirit of nebula 3 and uses a lot of lowlevel code, but all the rendering and other integration code is completely redesigned. It is not complete in any way currently and there is no involvement of Radonlabs (or any former employees) in this project either.

**Comment by 4censord** [comment]
i see, thanks for clearing that up for me.

Has anyone ever tried to port a game from nebula {2,3} to this?

**Comment by kaffeewolf** [comment]
Technically that should be possible but most certainly a lot of work. The game application layer is fairly untouched, but then again, nebula 3 wasnt finished at the time either, so it depends on when the game was made. 

I am not aware of any (public) endeavors that tried to port to it, but it would surely be interesting! 
This variant of nebula wouldnt be suitable, the application layer is more or less gone
