### ISSUE TITLE
Vulkan init error and errors on run tests 

### ISSUE THREAD

**Issue by happydpc** [gscept/nebula#20]
Error with "Vulkan get function proc". I am using vulkan sdk 1.2.135.0. 

![image](https://user-images.githubusercontent.com/771776/85301122-03edae80-b4da-11ea-962e-05c0538697a0.png)

![image](https://user-images.githubusercontent.com/771776/85301160-123bca80-b4da-11ea-8803-e6a2892b18d1.png)

**Comment by Duttenheim** [comment]
Hi! I have my suspicions why you get this error. Apparently, nvidia decided to remove a bunch of vulkan core functions in their latest canonical drivers, however, if you download their Vulkan specific drivers, this problem should sort itself out :).

**Comment by happydpc** [comment]
Aha, Install the Nvidia Vulkan driver the problem solved.But here comes the new error:

This is the testviewer's error:  
![image](https://user-images.githubusercontent.com/771776/85354344-f0276400-b53c-11ea-971a-f66f2401f89a.png)

This is the testrender's error:

![image](https://user-images.githubusercontent.com/771776/85354645-a25f2b80-b53d-11ea-9c17-98a1a0baf2bf.png)

**Comment by happydpc** [comment]
Maybe I have missed something, but there's no tutorial about this. Thank you.
![image](https://user-images.githubusercontent.com/771776/85354883-17cafc00-b53e-11ea-9d1e-41ced7214669.png)

**Comment by Duttenheim** [comment]
Ah, sorry for not replying to this. 

So it seems you don't have content built. I am afraid a lot has changed since you last tried this. Probably what you'd need to do is to grab the latest version of the engine, which know contains the asset batcher which would resolve this issue. Please let me know if you decide to try this again.

**Comment by fLindahl** [comment]
Stale issue
