### ISSUE TITLE
Double gamma correction applied to final image

### ISSUE THREAD

**Issue by fLindahl** [gscept/nebula#228]
It seems like we're applying double gamma correction to the final image.

![image](https://github.com/user-attachments/assets/f3dbd3af-30e6-4450-a17e-72376d67c12a)

Left is unlit base color in nebula, and right is unlit basecolor in GLTF sampler viewer.

If we apply an inverse gamma correction in finalize, we get this:

![image_2024-11-08_22-02-04](https://github.com/user-attachments/assets/0f6c1587-9226-4ca0-8d3b-71480fe71ccf)

Which looks a lot better.

**Comment by Duttenheim** [comment]
Caused by texconv not using sRGB formats when converting textures. Compressonator currently lacks support for this, which is a shame and which is why we can't reliably use Compressonator.
