### ISSUE TITLE
Nebula main branch does not compile on Ubuntu 1910

### ISSUE THREAD

**Issue by tpanj** [gscept/nebula#3]
**./fips build**
```
  Generator

    Unix Makefiles

  does not support platform specification, but platform

    x64

  was specified.
```
**./fips physx build**
```
[ERROR] expected compiler target (win-vs15, win-vs16)
```
**My System:**
$ python --version
Python 3.7.5

$ cmake --version
cmake version 3.13.4

**Comment by Duttenheim** [comment]
We're aware that currently, Nebula does not build on Linux based OS:es. Unfortunately, we're all focused on the Windows version at the moment, so if you want to build Nebula and try it out, that's the platform we can claim that we fully support.

**Comment by kaffeewolf** [comment]
Nebula should build on linux (CI is currently using ubuntu 18.04 and a recent clang). There are some issues with the vulkan loader, cmake adds -rdynamic to the executables flags and that somehow breaks the dynamic loading of vulkan functions. Apart from that most of the stuff works
