### ISSUE TITLE
how to build on Unix?

### ISSUE THREAD

**Issue by tree786** [gscept/nebula#49]
Hillo

I have git clone the repo, and trying to build using cmake, but I get error:

```
CMake Error at CMakeLists.txt:10 (include):
  include could not find requested file:

    /home/../Desktop/fips/cmake/fips.cmake


CMake Error at CMakeLists.txt:11 (fips_setup):
  Unknown CMake command "fips_setup".

```
I dont know what fips is or how to install on arch (i on manjaro). Do you have an idea of how to build on unix?

Tschuss

**Comment by kaffeewolf** [comment]
Nebula compiles with the help of [fips](https://floooh.github.io/fips/), which is a wrapper on top of cmake written in Python.  You don't need to install anything besides Python (and the other deps listed), just running 
`./fips set config vulkan-linux-ninja-debug.yml`
and then the rest of the instructions (`./fips gen && ./fips build`) should do the trick, it will download dependencies as needed. Be aware that it will download external libraries in the parent folder of your checkout, so you may want to place it in a folder of its own

**Comment by tree786** [comment]
Thanks for the info ! I have now tried running these commands, but I get an error part way :
```
[ERROR] No configs found for 'vulkan-linux-ninja-debug.yml'
```
It downloads some of the dependency but that stops at that ^^ error. Is there some manual flag/config setting i need to set for it?
